In [165]:
# bias co he so ung voi weight (0,0), 2 input have weights (1, 0), (2, 0)

In [166]:
import numpy as np

In [167]:
input = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

In [168]:
input

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [169]:
numInput = 4

In [170]:
expect_out = np.array([[0],[0],[0],[1]])

In [171]:
expect_out

array([[0],
       [0],
       [0],
       [1]])

In [172]:
bias = np.random.randn(1, 1)

In [173]:
learning_rate = 0.1

In [174]:
# weights = 1 * 2.*np.random.rand(3,1)
weights = np.random.randn(2,1)

In [175]:
# weights[1] = -weights[1]

In [176]:
weights

array([[-0.22323955],
       [-0.98040475]])

In [177]:
iterations = 8000

In [178]:
# ham sigmoid chuan hoa du lieu
def sigmoid(x):
    return 1. / (1. + np.exp(-x))

In [179]:
# DAO HAM SIGMOID
def sigmoid_derivative(x):
    return sigmoid(x) * (1. - sigmoid(x))

In [180]:
# for i in range(iterations):
#     out = np.zeros((4,1))
#     for j in range(numInput):
#         y = bias * weights[0,0] + input[j, 0] * weights[1,0] + input[j, 1] * weights[2,0]
# #         y = weights[0,0] + input[j, 0] * weights[1,0] + input[j, 1] * weights[2,0]
#         out[j] = 1. / (1. + np.exp(-y))
#         delta = expect_out[j] - out[j]
#         weights[0,0] = weights[0,0] + coeff *bias * delta
#         weights[1,0] = weights[1,0] + coeff * input[j, 0] * delta
#         weights[2,0] = weights[2,0] + coeff * input[j, 1] * delta
#         print ("loss: ", delta)
#     print (out)
#     print (delta)

In [181]:
for j in range(numInput):
    print(expect_out[j])


[0]
[0]
[0]
[1]


In [182]:
for i in range(iterations):
    out = np.zeros((4,1))
    for j in range(numInput):
#         y = bias * weights[0,0] + input[j, 0] * weights[1,0] + input[j, 1] * weights[2,0]
        z1 = bias + input[j, 0] * weights[0, 0] + input[j, 1] * weights[1, 0]
        a1 = sigmoid(z1)
        out[j] = a1
        error = a1 - expect_out[j]
        
        # backpropagation
        delta_bias = sigmoid_derivative(z1)
        delta_weights00 = sigmoid_derivative(z1) * input[j, 0]
        delta_weights01 = sigmoid_derivative(z1) * input[j, 1]
        
        bias -= learning_rate * error * delta_bias
        weights[0, 0] -= learning_rate * error * delta_weights00
        weights[1, 0] -= learning_rate * error * delta_weights01
#         print ("loss: %s", error)
    print (out)

[[ 0.46278762]
 [ 0.24213027]
 [ 0.40412334]
 [ 0.19898907]]
[[ 0.45957887]
 [ 0.24130596]
 [ 0.40177519]
 [ 0.19878817]]
[[ 0.45641937]
 [ 0.24052069]
 [ 0.39949187]
 [ 0.19862968]]
[[ 0.45330862]
 [ 0.23977381]
 [ 0.39727244]
 [ 0.19851308]]
[[ 0.45024614]
 [ 0.23906465]
 [ 0.39511595]
 [ 0.19843789]]
[[ 0.44723138]
 [ 0.2383926 ]
 [ 0.39302146]
 [ 0.19840364]]
[[ 0.44426381]
 [ 0.23775703]
 [ 0.39098802]
 [ 0.19840989]]
[[ 0.44134287]
 [ 0.23715733]
 [ 0.38901468]
 [ 0.1984562 ]]
[[ 0.43846798]
 [ 0.23659292]
 [ 0.3871005 ]
 [ 0.19854218]]
[[ 0.43563855]
 [ 0.23606321]
 [ 0.38524452]
 [ 0.19866741]]
[[ 0.43285399]
 [ 0.23556765]
 [ 0.38344581]
 [ 0.19883154]]
[[ 0.43011369]
 [ 0.23510568]
 [ 0.38170344]
 [ 0.19903421]]
[[ 0.42741702]
 [ 0.23467677]
 [ 0.38001647]
 [ 0.19927508]]
[[ 0.42476338]
 [ 0.23428038]
 [ 0.378384  ]
 [ 0.19955382]]
[[ 0.42215211]
 [ 0.23391602]
 [ 0.3768051 ]
 [ 0.19987013]]
[[ 0.4195826 ]
 [ 0.23358318]
 [ 0.37527888]
 [ 0.20022373]]
[[ 0.4170542 ]
 [ 0.2332