# code xor use neural network

In [55]:
# ta su dung hai duong thang de phan biet hai cap diem
# sau do ta su dung mot lop neural de phan biet tiep
# z1 = x1 * w1 + x2 * w2 + b1
# z2 = x1 * w3 + x2 * w4 + b2
# a1 = g(z1)
# a2 = g(z2)
# z3 = theta1 * a1 + theta2 * a2 + c
# a3 = g(z3)
# cost functioin 1/2 * (h(x)^2 - y)

In [56]:
import numpy as np


In [57]:
input = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
input

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [58]:
numInput = 4

In [59]:
expect_out = np.array([[0], [1], [1], [0]])

In [60]:
expect_out

array([[0],
       [1],
       [1],
       [0]])

In [61]:
weight = np.random.randn(2, 2)

In [62]:
weight

array([[-0.51489935, -0.99792684],
       [ 0.95064456,  0.03390488]])

In [63]:
bias = np.random.randn(2, 1)

In [64]:
theta = np.random.randn(2, 1)

In [65]:
c = np.random.randn(1, 1)

In [66]:
learning_rate = 0.7

In [67]:
# ham sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

In [68]:
iterations = 6000

In [69]:
for i in range(iterations):
    out = np.zeros((4, 1))
    for j in range(numInput):
        # feed forward
        z1 = input[j, 0] * weight[0, 0] + input[j, 1] * weight[0, 1] + bias[0,0]
        z2 = input[j, 0] * weight[1, 0] + input[j, 1] * weight[1, 1] + bias[1,0]
        a1 = sigmoid(z1)
        a2 = sigmoid(z2)
        z3 = theta[0, 0] * a1 + theta[1, 0] * a2 + c
        a3 = sigmoid(z3)
        
        out[j] = a3
        
        # error 
        error = (a3 - expect_out[j])
        
        # backpropagation
        delta_theta00 = sigmoid_derivative(z3) * a1
        delta_theta10 = sigmoid_derivative(z3) * a2
        delta_c = sigmoid_derivative(z3)
        delta_b00 = sigmoid_derivative(z3) * theta[0, 0] * sigmoid_derivative(z1) 
        delta_b10 = sigmoid_derivative(z3) * theta[1, 0] * sigmoid_derivative(z2)
        delta_w00 = sigmoid_derivative(z3) * theta[0, 0] * sigmoid_derivative(z1) * input[j, 0]
        delta_w01 = sigmoid_derivative(z3) * theta[0, 0] * sigmoid_derivative(z1) * input[j, 1]
        delta_w10 = sigmoid_derivative(z3) * theta[1, 0] * sigmoid_derivative(z2) * input[j, 0]
        delta_w11 = sigmoid_derivative(z3) * theta[1, 0] * sigmoid_derivative(z2) * input[j, 1]
        
        # update parameter
        theta[0, 0] -= error * learning_rate * delta_theta00
        theta[1, 0] -= error * learning_rate * delta_theta10
        c -= error * learning_rate * delta_c
        bias[0, 0] -= error * learning_rate * delta_b00
        bias[1, 0] -= error * learning_rate * delta_b10
        weight[0, 0] -= error * learning_rate * delta_w00
        weight[0, 1] -= error * learning_rate * delta_w01
        weight[1, 0] -= error * learning_rate * delta_w10
        weight[1, 1] -= error * learning_rate * delta_w11
        
        
    print (out)
print ("weight[0, 0]: %s", weight[0, 0])
print ("weight[0, 1]: %s", weight[0, 1])
print ("weight[1, 0]: %s", weight[1, 0])
print ("weight[1, 1]: %s", weight[1, 1])
print ("bias[0, 0]: %s", bias[0, 0])
print ("bias[1, 0]: %s", bias[1, 0])


[[ 0.51046581]
 [ 0.40604951]
 [ 0.33211602]
 [ 0.34863135]]
[[ 0.54434106]
 [ 0.44110839]
 [ 0.36535938]
 [ 0.38515702]]
[[ 0.56776484]
 [ 0.46595526]
 [ 0.3901005 ]
 [ 0.41104546]]
[[ 0.58349611]
 [ 0.48283006]
 [ 0.40798011]
 [ 0.42888275]]
[[ 0.59390106]
 [ 0.49397963]
 [ 0.42079142]
 [ 0.44105319]]
[[ 0.60070505]
 [ 0.5011723 ]
 [ 0.43001411]
 [ 0.44935199]]
[[ 0.605093  ]
 [ 0.50567762]
 [ 0.43674559]
 [ 0.45503534]]
[[ 0.60786166]
 [ 0.508373  ]
 [ 0.44176206]
 [ 0.45895793]]
[[ 0.60954367]
 [ 0.50985512]
 [ 0.44560045]
 [ 0.4616953 ]]
[[ 0.61049512]
 [ 0.51052711]
 [ 0.44862812]
 [ 0.4636338 ]]
[[ 0.61095452]
 [ 0.51066058]
 [ 0.4510951 ]
 [ 0.46503266]]
[[ 0.61108194]
 [ 0.51043837]
 [ 0.45317121]
 [ 0.46606599]]
[[ 0.61098508]
 [ 0.5099835 ]
 [ 0.45497168]
 [ 0.46685083]]
[[ 0.61073652]
 [ 0.50937875]
 [ 0.45657477]
 [ 0.46746599]]
[[ 0.61038526]
 [ 0.50867979]
 [ 0.45803373]
 [ 0.46796463]]
[[ 0.60996445]
 [ 0.50792406]
 [ 0.45938487]
 [ 0.46838265]]
[[ 0.60949654]
 [ 0.5071

In [70]:
def feed_forward(x1, x2):
    z1 = x1 * weight[0, 0] + x2 * weight[0, 1] + bias[0,0]
    z2 = x1 * weight[1, 0] + x2 * weight[1, 1] + bias[1,0]
    a1 = sigmoid(z1)
    a2 = sigmoid(z2)
    z3 = theta[0, 0] * a1 + theta[1, 0] * a2 + c
    a3 = sigmoid(z3)
    print (a3)

In [71]:
x1 = 1
x2 = 0.01

In [72]:
feed_forward(x1, x2)

[[ 0.9817409]]
